# Generated by Django 4.2.2 on 2023-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_ta_info_is_logged"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Roll", models.CharField(default=None, max_length=100)),
                ("Password", models.CharField(default=None, max_length=50)),
                ("is_logged", models.BooleanField(default=False)),
            ],
        ),
    ]
