# Generated by Django 4.2.2 on 2023-06-29 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_student_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                ("courseCode", models.CharField(default=None, max_length=5)),
                (
                    "courseId",
                    models.CharField(
                        default=None, max_length=5, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="admin_info",
            name="id",
        ),
        migrations.RemoveField(
            model_name="student_info",
            name="id",
        ),
        migrations.RemoveField(
            model_name="ta_info",
            name="id",
        ),
        migrations.AlterField(
            model_name="admin_info",
            name="Username",
            field=models.CharField(
                default=None, max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="student_info",
            name="Roll",
            field=models.CharField(
                default=None, max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="ta_info",
            name="Roll",
            field=models.CharField(
                default=None, max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="student_info",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.courses",
            ),
        ),
        migrations.AddField(
            model_name="ta_info",
            name="course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.courses",
            ),
        ),
    ]
