# Generated by Django 4.2.2 on 2023-06-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_admin_info_password_alter_admin_info_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_info",
            name="course",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.courses",
            ),
        ),
        migrations.AlterField(
            model_name="ta_info",
            name="course",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.courses",
            ),
        ),
    ]
