# Generated by Django 4.2.2 on 2023-06-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alter_student_info_course_alter_ta_info_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_info",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.courses"
            ),
        ),
        migrations.AlterField(
            model_name="ta_info",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.courses"
            ),
        ),
    ]
