# Generated by Django 4.2.2 on 2023-06-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_student_info_course_alter_ta_info_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courses",
            name="courseCode",
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name="courses",
            name="courseId",
            field=models.CharField(
                default=None, max_length=5, primary_key=True, serialize=False
            ),
        ),
    ]
