# Generated by Django 4.2.2 on 2023-06-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_student_info_course_alter_ta_info_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_info",
            name="course",
        ),
        migrations.RemoveField(
            model_name="ta_info",
            name="course",
        ),
    ]
