# Generated by Django 4.2.2 on 2023-06-29 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_remove_student_info_course_remove_ta_info_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_info",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.courses"
            ),
        ),
        migrations.AddField(
            model_name="ta_info",
            name="course",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.courses"
            ),
        ),
    ]
