# Generated by Django 4.2.2 on 2023-07-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_student_info_name_ta_info_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance_sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CourseId", models.CharField(default="", max_length=5)),
                ("Date", models.DateField(default="")),
                ("Start", models.TimeField(default="")),
            ],
        ),
    ]
